allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': false
  esbuild: true
  prisma: true
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@sentry/cli'
  - prisma
  - '@prisma/engines'
  - esbuild
  - sharp
